apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: go-server
spec:
  selector:
    app: go-server-container
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 7011
