apiVersion: v1
kind: Namespace
metadata:
  name: go-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server-container
  template:
    metadata:
      labels:
        app: go-server-container
    spec:
      containers:
      - name: go-server-container
        image: kyosifov/go-server:1.0.0
        ports:
        - containerPort: 7011
